### ISSUE TITLE
希望能够实现xml中书写sql的功能

### ISSUE THREAD

**Issue by cmdares** [E7du/jfinal-ext3#2]
可以参考jfinal ext的SqlInXmlPlugin功能

**Comment by qicz** [comment]
已经在考虑合并ext相关的功能(可以查看ext分支)，具体时间节点没有确定。 现在你可以先用
```java
 <dependency>
	<groupId>com.jfinal</groupId>
	<artifactId>jfinal-ext3</artifactId>
	<version>4.0.0-SNAPSHOT</version>
</dependency>
```
我已经将SqlInXmlPlugin和ConfigPlugin合并并测试过了。

**Comment by cmdares** [comment]
感谢。
由于一些项目以前使用mybatis。存在大量的复杂sql。语句长且有一定的动态性，如果都写到源码中。日后维护存在很大的负担。同时在要求多库的情况，下牵扯到sql的移植和修改。那么sql统一管理尤其显得非常重要。所以希望能够早日在您的发布版本中应用到这个特性。

**Comment by cmdares** [comment]
顺办在说个想法。经过我们软件开发在行业中的复杂性来看，希望能够通过框架把xml中的sql片段，能否考虑形成一个sql 配置数据表，将一些业务的sql语句写入到表中。这样做有一定好处。可以规范程序开发模式和及时调整业务逻辑。可以通过管理的方法修改数据库中的sql逻辑。达到不停系统热更新。可以考虑周期扫描书库时间戳的变动更新程序sql缓存的方式，防止并发扫描元数据。
目前我在mybatis上已经把mapper管理接管到了数据库元数据——即sql片段的书写存在数据，mapper加载直读数据库。已经体验到了管理的便捷性。同时在后期数据库优化。这种做法的好处也是非常明显的。
看看您是否能够理解我的这个想法。是否可以开启这个特性。把jf的后台在开发和运维上再进行一次提速！
我可以共享一下元数据表的格式。您可以做个参考：
SQLID（必须，且唯一）、业务模块（可选）、数据源ID（目的为了配合多库）、SQL脚本（必须，可以使用xml来书写，--可变量绑定、动态片段等特性）、SQL逻辑说明（可选，为了日后做业务逻辑的解读）、更新时间（时间戳 必须，为了支持动态扫描更新缓存）

**Comment by qicz** [comment]
好建议。ext之外，此方案，很久以前就考虑过，不过有几个问题：1. 复杂sql过多，是不是数据库设计就有问题？2.复杂sql过多，是不是可以拆分sql？
另外，如果你自己这样的需求，完全可以自己做一个数据库，然后Ge一下，拿到Model，自己就可以玩啦。

ext的特性合并到ext3，需要时间，我现在是闲暇才会coding，所以我尽快的吧。

**Comment by qicz** [comment]
**4.0.0**
加入 Xls 读写，XlsRender，SqlInXmlPlugin等，已同步到 central。
